name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        buffer_size: [1, 32, 1024]
    env:
      BUFFER_SIZE: ${{ matrix.buffer_size }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y valgrind

      - name: Build harness
        run: make

      - name: Run unit tests
        run: make test

      - name: Run Valgrind tests
        run: |
          make clean
          make valgrind-test DEBUG=1
